// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYBJHTUymios0nYW9ESeiZEd3un0mwKOs',
    appId: '1:970765470269:web:01f9dbe915ba5a4d46b854',
    messagingSenderId: '970765470269',
    projectId: 'kash-book',
    authDomain: 'kash-book.firebaseapp.com',
    storageBucket: 'kash-book.appspot.com',
    measurementId: 'G-L8R9JJ9P6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn-blUOQjzYj8zMveAF43IMcGJRNbKMp0',
    appId: '1:970765470269:android:2b90c27742a6dcda46b854',
    messagingSenderId: '970765470269',
    projectId: 'kash-book',
    storageBucket: 'kash-book.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDgsm8yAUYubS2A_9vDpqwrT5WeITLc40',
    appId: '1:970765470269:ios:27f3a098bac3a9bb46b854',
    messagingSenderId: '970765470269',
    projectId: 'kash-book',
    storageBucket: 'kash-book.appspot.com',
    iosBundleId: 'com.example.kashbookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDgsm8yAUYubS2A_9vDpqwrT5WeITLc40',
    appId: '1:970765470269:ios:6f56f7fc96f81abe46b854',
    messagingSenderId: '970765470269',
    projectId: 'kash-book',
    storageBucket: 'kash-book.appspot.com',
    iosBundleId: 'com.example.kashbookApp.RunnerTests',
  );
}
