import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

final selectedIconProvider = StateProvider<IconData?>((ref) => null);

const icons = [
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.cableCar,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.utensils,
];
